title: UserFrosting
author:
  name: Alex Weissman
metadata:
    description: 'UserFrosting is a web framework and user management application for PHP.'

redirects:
    /gallery: 'http://v3.userfrosting.com/gallery'
    /installation: 'https://learn.userfrosting.com/basics/installation'
    /troubleshooting: 'https://learn.userfrosting.com/basics/getting-help'
    /navigating: 'https://learn.userfrosting.com/basics/overview'
    /components: '/features'
    /security: 'https://learn.userfrosting.com/security'
    /plugins: 'https://learn.userfrosting.com/sprinkles'
